#!/bin/sh -f 

save_dir=`pwd`

#./check_app _upgrade '_upgrade not found.'
#use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi
build_dir=`pwd`

#//////////////////////////////////////////////
#/// inlib ////////////////////////////////////
#//////////////////////////////////////////////
cd ${build_dir}
from=${save_dir}/../../../inexlib/inlib/examples/cpp
/bin/cp ${from}/hcontest.cpp .
/bin/cp ${from}/gen_data.cpp .

# histo :
/bin/mkdir -p ${build_dir}/inlib/histo
cd ${build_dir}/inlib/histo
from=${save_dir}/../../../inexlib/inlib/inlib/histo
/bin/cp ${from}/axis .
/bin/cp ${from}/axes .
/bin/cp ${from}/histo_data .
/bin/cp ${from}/base_histo .
/bin/cp ${from}/b1 .
/bin/cp ${from}/b2 .
/bin/cp ${from}/b3 .
/bin/cp ${from}/h1 .
/bin/cp ${from}/h1d .
/bin/cp ${from}/h2 .
/bin/cp ${from}/h2d .
/bin/cp ${from}/h3 .
/bin/cp ${from}/h3d .

/bin/cp ${from}/profile_data .
/bin/cp ${from}/p1 .
/bin/cp ${from}/p1d .
/bin/cp ${from}/slice .
/bin/cp ${from}/sliced .

/bin/cp ${from}/shisto_data .
/bin/cp ${from}/base_shisto .
/bin/cp ${from}/sb1 .
/bin/cp ${from}/sb2 .
/bin/cp ${from}/sh1 .
/bin/cp ${from}/sh1d .
/bin/cp ${from}/sh2 .
/bin/cp ${from}/sh2d .

# inlib :
/bin/mkdir -p ${build_dir}/inlib
cd ${build_dir}/inlib
from=${save_dir}/../../../inexlib/inlib/inlib
/bin/cp ${from}/mapmanip .
/bin/cp ${from}/mem .
/bin/cp ${from}/forit .
/bin/cp ${from}/typedefs .
/bin/cp ${from}/S_STRING .
/bin/cp ${from}/cmathT .
/bin/cp ${from}/mathd .
/bin/cp ${from}/randT .
/bin/cp ${from}/rtausmed .
/bin/cp ${from}/rtausmeui .
/bin/cp ${from}/randd .
/bin/cp ${from}/vdata .

/bin/cp ${from}/args .
/bin/cp ${from}/sout .
/bin/cp ${from}/strip .
/bin/cp ${from}/words .
/bin/cp ${from}/sto .

# inlib/sys :
/bin/mkdir -p ${build_dir}/inlib/sys
cd ${build_dir}/inlib/sys
from=${save_dir}/../../../inexlib/inlib/inlib/sys
/bin/cp ${from}/atime .

cd ${save_dir}


